### PR TITLE
Invoke controller asynchronously when handling messages

### PR DESCRIPTION
**Pull request by tessellator**
This commit updates the connector to invoke the controller
asynchronously when handling messages from the Kafka topic. If the
messages are invoked synchronously, we are artificially limiting the
invocation rate to the handling rate of a single instance of a
function. This is essentially eliminating the advantage of autoscaling.
Invoking the controller asynchronously restores that advantage.

Signed-off-by: Chad Taylor <taylor.thomas.c@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Another approach for this may be to invoke the async-function endpoint as a control option. This would be useful for when the topic is frequently saturated.

**Comment by tessellator** [comment]
I would be concerned about using the `async-function` endpoint in this connector for a couple of reasons. 

First, it would require us to set up and handle a callback URL. This would add a fair bit of complexity, including setting up the web server and handler and specifying a URL for the callback. If this connector were truly fire-and-forget, this would not be necessary. However, having a callback URL would be needed in order to print the response bodies as we do now.

Second, invoking the `async-function` endpoint would mean that we lose the context in which individual calls are made. An [open issue](https://github.com/openfaas-incubator/kafka-connector/issues/20) asks for retry behavior to be added to this connector. My concern would be that we would no longer have the original message used when receiving a response via a callback URL and thus would not have enough information to invoke the function again. This is possible using the `function` endpoint, although admittedly, it would likely require adding the original message to the InvokerResponse in the connector-sdk.

That said, using the `async-function` endpoint would prevent long-runnning functions from eating up the connection pool available to the client. I have not tested it, but I imagine you could deplete the pool and be limited to the throughput of your slowest function. I assume this is what you meant when referring to saturated topics.

I am unsure how you what you want to choose from this set of trade-offs. I would be happy to implement the `async-function` approach in another PR if you would like to compare them side-by-side.

**Comment by daikeren** [comment]
Hi @alexellis 

I’m trying to use kafka-connector for some long-running function ( > 30s ). As I see in

https://github.com/openfaas-incubator/kafka-connector/pull/27 and
https://github.com/openfaas-incubator/connector-sdk/issues/1

Looks like one way to do this is to invoke function via async route and I would like to try to add this feature to connector-sdk, Do you have any though on this?

**Comment by martindekov** [comment]
Hello @tessellator implemented the change in the connector sdk [here](https://github.com/openfaas-incubator/connector-sdk/pull/23) with the async route and manually vendored in the kafka-connector. It seemed to work out of the box.

**Comment by tessellator** [comment]
Closing in favor of #46

**Pull request closed without merging**
