### PR TITLE
Add one liner to view topic messages

### PR DESCRIPTION
**Pull request by rgee0**
A quick addition of a one-liner in README to help people wishing to verify messages are making it onto a given topic.

Signed-off-by: Richard Gee <richard@technologee.co.uk>

### CODE REVIEW

**Comment by tessellator** [comment]
I confirmed this to work and find it super useful! :)

**Comment by alexellis** [comment]
Nice work. Not sure how I missed this. cc @martindekov

**Comment by martindekov** [comment]
Thanks for pinging me Alex I might need this 👍

**Comment by alexellis** [comment]
Let's put it in the blog that's being written too?

**Comment by martindekov** [comment]
Good idea I will put it

**Pull request merged**
