### PR TITLE
Add the SDK changes for multitopics

### LINKED ISSUE #41: Vendor 0.4.0 of connector-sdk
## Expected Behaviour

Vendor 0.4.0 of connector-sdk so that multiple functions can be invoked from a single topic annotation 

## Current Behaviour

A function can only subscribe to one topic

* Update Gopkg.toml to [0.4.0](https://github.com/openfaas-incubator/connector-sdk/releases/tag/0.4.0)
* Run `dep ensure`
* Add env-var for topic separator and expose in README (not required for helm chart at this point)

### PR DESCRIPTION
**Pull request by rgee0**
This change enables functions to listen to multiple topics.  Prior to this
the connector could listen to multiple topics but would read a function's topic
annotation as a single value.  Following changes to the SDK annotations can now
be multiple delimited topics.  The delimiter defaults to a comma and can be
over-ridden using the `topic_delimiter` env var.

Associated changes have been made to the README - to surface the availability of
the variable, and to  `connector-dep.yml` for similar reasons.

Fixes #41 

Signed-off-by: Richard Gee <richard@technologee.co.uk>

## Testing:
```
$ export TAG=0.4.0
$ export NAMESPACE=rgee0
$ make build push
```
Consequently `rgee0/kafka-connector:0.4.0` is available on Docker Hub.

```
$ helm upgrade kafka-connector openfaas/kafka-connector --install --namespace openfaas --set image=rgee0/kafka-connector:0.4.0 --set topics="cats\,not-cats" --set print_response_body=true

Release "kafka-connector" has been upgraded. Happy Helming!
LAST DEPLOYED: Mon Apr 22 18:17:45 2019
NAMESPACE: openfaas
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME             DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
kafka-connector  1        1        1           0          9d

==> v1/Pod(related)
NAME                              READY  STATUS             RESTARTS  AGE
kafka-connector-5fc8958bd4-sjmlf  1/1    Terminating        5         9d
kafka-connector-7fdd98bdd9-rh57b  0/1    ContainerCreating  0         0s

NOTES:
Thanks for installing kafka-connector. Please follow the instructions below to get you started.

You can watch the Connector logs to see it invoke your functions:

$ kubectl logs -n openfaas deploy/kafka-connector -f
```

Tracking the logs:

```
$ kubectl logs -n openfaas deploy/kafka-connector -f

2019/04/22 17:17:53 Syncing topic map
2019/04/22 17:17:54 Binding to topics: [cats not-cats]
Rebalanced: &{Type:rebalance start Claimed:map[] Released:map[] Current:map[]}
Rebalanced: &{Type:rebalance OK Claimed:map[cats:[0] not-cats:[0]] Released:map[] Current:map[cats:[0] not-cats:[0]]}
2019/04/22 17:17:56 Syncing topic map
...
2019/04/22 17:22:05 Syncing topic map
[#1] Received on [not-cats,0]: '{detail}
2019/04/22 17:22:07 Invoke function: db-stasher
2019/04/22 17:22:07 Invoke function: twitter-notifier
2019/04/22 17:22:07 connector-sdk got result: [200] not-cats => db-stasher (14) bytes
[200] not-cats => db-stasher
value inserted
2019/04/22 17:22:09 connector-sdk got result: [200] not-cats => twitter-notifier (0) bytes
[200] not-cats => twitter-notifier
2019/04/22 17:22:11 Syncing topic map
```

Shows 2 functions being invoked on `not-cats`, however, this was always possible.  `db-stasher` is configured to listen to both `not-cats` and `cats`:

```
$ kubectl describe -n openfaas-fn deploy/db-stasher
Name:                   db-stasher
Namespace:              openfaas-fn
Annotations:            deployment.kubernetes.io/revision: 7
                        prometheus.io.scrape: false
                        topic: cats,not-cats
```

So should now also be triggered by the `cats` topic.

```
2019/04/22 17:37:14 Syncing topic map
2019/04/22 17:37:17 Invoke function: db-stasher
[#2] Received on [cats,0]: '{detail}'
[200] cats => db-stasher
value inserted
2019/04/22 17:37:17 Invoke function: slack-notifier
2019/04/22 17:37:17 connector-sdk got result: [200] cats => db-stasher (14) bytes
2019/04/22 17:37:17 Syncing topic map
[200] cats => slack-notifier
Message successfully sent to channel at 1555954638.000100OK
2019/04/22 17:37:18 connector-sdk got result: [200] cats => slack-notifier (70) bytes
2019/04/22 17:37:20 Syncing topic map
```

### CODE REVIEW

**Comment by rgee0** [comment]
The image in `connector_dep.yml` will need updating

**Comment by martindekov** [comment]
Sorry Richard, though I gave the output of the testing ...

**Comment by alexellis** [comment]
Me too, is it ready to merge? @rgee0 @martindekov 

Sometimes I've confused PRs on the connector-sdk with ones on a specific implementation. Maybe that's what happened here?

**Comment by martindekov** [comment]
Yeah ^ Othewise I believe it is ready to merge 👍

**Comment by martindekov** [comment]
Then I can rebase mine

**Comment by alexellis** [comment]
Merged :+1: please go ahead

**Comment by alexellis** [comment]
Thanks @rgee0 :clap:

**Pull request merged**
