### PR TITLE
Add configuration for port

### LINKED ISSUE #48: Make default port configurable
Currently the default port is not configurable and it is stuck on 9092. Someone can have development kafka running on different port.

## Expected Behaviour

Add environmental variable which configures default port and another one enabling disabling the behaviour and providing with custom port. 

## Current Behaviour

Port is non configurablr

## Possible Solution

Check Expected behaviour paragraph

## Steps to Reproduce (for bugs)

1.Run kafka Broker on port different than 9092
2.Connector cannot subscribe on it

## Context

Check description.
  
## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
N/A
* Kafka version and configuration:
N/A
* Docker version `docker version` (e.g. Docker 17.0.05 ):
N/A
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
N/A
* Link to your project or a code example to reproduce issue:
N/A
* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

### PR DESCRIPTION
**Pull request by martindekov**
Adding configuration for port, as the
current functionality always went with
9092

Closes #48 

Signed-off-by: Martin Dekov <mdekov@vmware.com>

### CODE REVIEW

**Comment by martindekov** [comment]
Hey @reitermarkus I think this is what you need.

**Comment by reitermarkus** [comment]
Thanks, however I would find it more intuitive if you could just specify either `broker_host: kafka` (which appends the default port) or `broker_host: kafka:29092`.

**Comment by martindekov** [comment]
Hey @reitermarkus I understand, your proposal is really more intuitive, but it will break in case someone has the image deployed with the already existing functionality. 

In other words, if some user used the old configuration `broker_host: kafka` and update the image with this change, the connector will seek only `kafka` without the port in case I made it like `broker_host: kafka:29092`. So the user would be prompted to update the image and configuration, which is also valid but I wanted to make it backward compatible.

**Comment by reitermarkus** [comment]
You can split the variable at `:`, and if the port part is empty, use the default port, this way it is backwards compatible.

**Comment by brynnonpicard** [comment]
@martindekov Any update on when this might be merged? I was hoping to use the Kafka connector in a production deployment of OpenFaaS, but I need to be able to use a custom port for security reasons.

**Comment by martindekov** [comment]
I will ping some of the contributors for review

**Comment by alexellis** [comment]
I'm surprised you that we didn't hit this earlier. Thank you for the fix Martin.

I might be missing something, but I am not sure why we need a custom port variable? Couldn't you just put the port in the broker string?

**Comment by alexellis** [comment]
Is this change backwards compatible or do people need to take some action to upgrade?

**Comment by alexellis** [comment]
I can see why we needed to take out the hard-coded port, but not sure about the env-var.

**Comment by burtonr** [comment]
I read it as needing the separate env var to ensure backwards compatability.

If someone has the kafka connection as `http://localhost`, it would be set as `http://localhost:9092` in the connector.

The envvar ensures that this remains true, while also providing the ability to change the port. Without the env var, the example above would end up at `http://localhost` in the connector (without the port). That's why the port couldn't be included in the broker string

**Comment by reitermarkus** [comment]
I still don't see the need for the `custom_port` variable. I explained above the you can just split the `broker_host` variable at `:` to see if it already contains a port.

**Comment by reitermarkus** [comment]
Example in Ruby since I don't know Go.

```ruby
host, port = ENV['broker_host'].split(':', 2)
port ||= '9092' 
broker_host = "#{host}:#{port}"
```

This is backwards/forwards-compatible:

- `http://localhost` -> `http://localhost:9092`
- `http://localhost:9092` -> `http://localhost:9092`
- `http://localhost:29092` -> `http://localhost:29092`

**Comment by martindekov** [comment]
Sorry for not responding, I was moving into a new place and am ready just now, the change can be reworked if requested, and it is the simplest solution I can think of, what if you'd like to have kafka accessible through http the I have two ’:‘ but then If I don't I need to check if there is http/https to be sure the : is the second place or not ... you get what I mean, I think this is the most straight forward approach, even though it might bot seem like that from the start.

**Comment by martindekov** [comment]
Actually I forgot why ai went that way :smile: now I remembered, in case multiple brokers is added we can just list the brokers and ports in order, so to make multiple brokers backward compatible we we would have broker_host: something, kafka, whatever and ports: 9092, 1334, 5555 and in order can be mapped something:9092 kafka:1334 whatever:5555 if I went with : now(which is totally legitimate) I could not achieve the backwards compatibility later

**Comment by martindekov** [comment]
Sorry I should have mentioned that when I opened the PR just slipped out of my head ...

**Comment by reitermarkus** [comment]
> if you'd like to have kafka accessible through http

We could split first at `://`, then a second time at `:`.

```ruby
broker_host = ENV['broker_host']

if broker_host.include?('://')
  scheme, host_and_port = broker_host.split('://', 2)
  scheme << '://'
else
  scheme, host_and_port = ['', broker_host]
end

host, port = host_and_port.split(':', 2)
port ||= '9092' 
broker = "#{scheme}#{host}:#{port}"
```

> I think this is the most straight forward approach

It might be the most straight-forward approach implementation-wise, but not when using it.

Your example with multiple brokers would be easy to implement, but 

```yml
broker_host: something,kafka,whatever
custom_port: 9092,1334,5555
```

is much more difficult to edit and less readable than

```yml
broker_host: something:9092,kafka:1334,whatever:5555
```

>  I could not achieve the backwards compatibility later

Why not? Split first at `,` and then map the values using the same function as before.

**Comment by martindekov** [comment]
Hey @reitermarkus, you are right it is a better UX I changed it, check out [the new PR](https://github.com/openfaas-incubator/kafka-connector/pull/53) :+1:

**Pull request merged**
