### PR TITLE
Add multiple brokers and ports support

### LINKED ISSUE #28: Proposal: Support for multiple brokers and different ports
The default port for kafka is `9092`, but sometimes for some reasons people may want to use different ports, so we can just add the full host location and port to be explicit about your configuration. Also from the code I saw we are forcing only 1 host, which I think can be remade similar to topics and use multiple brokers instead of one.

## Expected Behaviour

Use multiple brokers with hosts.

## Current Behaviour

Currently you are allowed only 1 broker and the port 9092 is appended, the only way around that would be to go into the code and re-build it.

## Possible Solution

Add multiple borkers separated with `,` similar to how we do it with the topics and instead of adding only the name of the host, we can add the name + port:

`broker_hosts:  broker.one:1234, broker.two:5678`

And append `9092` in case `:` is missing in the array or something.

Either way the code libraries use `[]brokers` instead of `broker` and ATM we are forcing the single broker in a way.

## Steps to Reproduce (for bugs)

1. Deploy kafka with multiple partitions and different brokers on different port
2. Try to consume topics

## Context

Extends Issue #21 Also using the solution at work where there are multiple broker hosts, with default ports, but still

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Not relevant
* Kafka version and configuration:
10.0 (re-compiled the code to use 10.0 Sarma client)
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Not relevant
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Not relevant
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N/A
* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

### PR DESCRIPTION
**Pull request by martindekov**
Adding support for multiple brokers and
different ports since until now the
port had to be 9092 and you could only have
one kafka broker

Closes #28 

Signed-off-by: mdekov <mdekov@vmware.com>

### CODE REVIEW

**Comment by reitermarkus** [comment]
@martindekov, any update on this?

**Comment by alexellis** [comment]
@martindekov could you rebase please? Btw why could users only have one connector?

@reitermarkus what is your current use-case for the connector? If we understand that a bit more how to develop the project.

**Comment by alexellis** [comment]
Do we want the relationship of 1-to-many between connectors and brokers? What requirement is driving that?

**Comment by reitermarkus** [comment]
I'm using it in a Docker Swarm, where I have Kafka with two listeners, one internal on port 9092 and one external on port 29092. (This is based on the `connector-swarm.kafka2.yml`, which is incorrect at the moment.) I would like to switch the ports, so that 9092 is the external port. I could map the port in Docker using `9092:29092`, but it would definitely be better (or less confusing) to have this functionality in `kafka-connector` instead.

**Comment by martindekov** [comment]
I haven't though of the scenario in which you can deploy the connector in multiple containers/pods and just have it like that. I think this is also valid use case, I can remove the part with multiple brokers if you'd only require the ports config. Saw the consumer that have list of brokers.

My personal opinion is that we should let the user decide whether he should go with multiple brokers, or deploy multiple pods/containers with different configuration, either way we force single broker now, I should add backwards compatibility though.

**Comment by reitermarkus** [comment]
Also, currently you are appending to the list which already contains `kafka:9092` instead of replacing the default value.

**Comment by martindekov** [comment]
Yes, you are right, I will need to refactor the code in general, nice observation there. By EOD tomorrow I will be done with this.

**Comment by martindekov** [comment]
Hey @reitermarkus updated the PR with your suggestion, now if the var does not exist we add the default broker. Otherwise this change is breaking which means anyone using kafka right now should update their ports. I would append the port `:9092` through code, but what if you have your kafka on different port? 

Otherwise I can add that (append port to values which does not contain it) to make it backward compatible, but not sure if this is desirable? would need input 

@alexellis WDYT?

**Comment by alexellis** [comment]
I'm not 100% clear yet, but I'll try to paraphrase. 

This PR is fixing a bug you found and adding a feature that no users have asked for yet. If that's the case, then let's fix the bug in a separate PR and then wait to see if there is demand or a need for the feature. 

Let me know if I'm missing something

**Comment by martindekov** [comment]
Maybe this needs two changes. First one is default configurable port(not added here) and the second is giving brokers as list(removing the default `:9092` port), rather than one single broker. I will add port configuration in separate PR as I would like to keep the single commit principle.

**Comment by alexellis** [comment]
Where is this today? Is it still required? cc @brynnonpicard

**Comment by martindekov** [comment]
I don't need the change anymore. We can close this one, if you request it 👍

**Comment by alexellis** [comment]
To clarify, my question is whether this functionality has been added. I think we updated to use a combined host and port didn't we?

**Comment by martindekov** [comment]
Ah, ok so this change was ment to add multiple hosts + ports. We added the multiple ports in another PR and this is left with only configuring multiple hosts, not sure if anyone needs this part. We can add it though.

**Comment by brynnonpicard** [comment]
I no longer have any need for these changes, since Ratehub has its own connector with this functionality.

**Pull request closed without merging**
