### PR TITLE
Fix typo in config.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by alexellis** [comment]
Hi I'm happy to merge this but it needs signing off with `git commit -s --amend` and a force push.

Thanks,

Alex

**Comment by reitermarkus** [comment]
Done.

**Comment by alexellis** [comment]
This is appreciated, and nice find on the typo. I'm going to enable the bot we use on this repo to give warnings about sign-off going forward.

**Comment by alexellis** [comment]
Ref: https://github.com/openfaas-incubator/kafka-connector/issues/12

**Pull request merged**
